=== lisad/draft-happel-mailmaint-pdparchive/schemas/address-book-schema.json
{
  "$id": "https://id.schemas.pub/o/DTI/PDPArchive/address-book",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Schema for Personal Data Portability Archive (pdparchive) Address Book",
  "type": "object",
  "required": ["@type", "uid", "updated", "name"],
  "$defs": {
    "rights": {
      "type": "object",
      "properties": {
        "mayRead": { "type": "boolean" },
        "mayWrite": { "type": "boolean" },
        "mayShare": { "type": "boolean" },
        "mayDelete": { "type": "boolean" }
      }
    }
  },
  "properties": {
    "@type": {
      "type": "string",
      "const": "AddressBook"
    },
    "uid": {
      "description": "Globally unique identifier for the address book",
      "type": "string"
    },
    "id": {
      "description": "JMAP server-set ID for the address book",
      "type": "string"
    },
    "updated": {
      "type": "string",
      "format": "date-time"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "description": {
      "type": ["string", "null"]
    },
    "sortOrder": {
      "type": "integer",
      "minimum": 0,
      "maximum": 2147483647
    },
    "isDefault": {
      "type": "boolean"
    },
    "isSubscribed": {
      "type": "boolean"
    },
    "shareWith": {
      "description": "Maps principal IDs to their rights; null if not shared",
      "type": ["object", "null"],
      "additionalProperties": {
        "$ref": "#/$defs/rights"
      }
    },
    "myRights": {
      "$ref": "#/$defs/rights"
    }
  }
}

=== lisad/draft-happel-mailmaint-pdparchive/examples/address-book2.json
{
   "$schema": "https://id.schemas.pub/o/DTI/PDPArchive/address-book",
   "@type": "AddressBook",
   "uid": "cd40089d-35f9-4fd7-980b-ba3a9f1d74fe",
   "updated": "2020-01-09T14:32:01Z",
   "name": "Autosaved",
   "description": null,
   "sortOrder": 1,
   "isDefault": false,
   "isSubscribed": true,
   "shareWith": null,
   "myRights": {
     "mayRead": true,
     "mayWrite": true,
     "mayShare": true,
     "mayDelete": false
   }
}

=== lisad/draft-happel-mailmaint-pdparchive/examples/address-book1.json
{
   "$schema": "https://id.schemas.pub/o/DTI/PDPArchive/address-book",
   "@type": "AddressBook",
   "uid": "062adcfa-105d-455c-bc60-6db68b69c3f3",
   "updated": "2020-01-09T14:32:01Z",
   "name": "Personal",
   "description": null,
   "sortOrder": 0,
   "isDefault": true,
   "isSubscribed": true,
   "shareWith": {
     "3f1502e0-63fe-4335-9ff3-e739c188f5dd": {
       "mayRead": true,
       "mayWrite": false,
       "mayShare": false,
       "mayDelete": false
     }
   },
   "myRights": {
     "mayRead": true,
     "mayWrite": true,
     "mayShare": true,
     "mayDelete": false
   }
}
